my_string = (input("Введите текст: "))
lenth = len(my_string)
print(lenth)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ", ""))
print(my_string[-1])
print(my_string[0])
